# Generated by Django 5.2.1 on 2025-05-19 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='admin', max_length=100)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quartier', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('description', models.JSONField(default=dict)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avance', models.IntegerField(default=1)),
                ('visite', models.DecimalField(decimal_places=2, default=2000, max_digits=15)),
                ('disponibilite', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.type')),
            ],
        ),
    ]
